# Generated by Django 5.2.3 on 2025-08-29 17:52

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='blank_profile.png', upload_to=users.models.Profile.user_profile_image_path),
        ),
    ]
