# Generated by Django 5.2.3 on 2025-09-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date_edited',
            field=models.BooleanField(default=False),
        ),
    ]
